# api/config/packages/api_platform.yaml
api_platform:
  swagger:
    api_keys:
      JWT:
        name: Authorization
        type: header
  exception_to_status:
    App\Exception\UserAlreadyExistsException: 409
    Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: 403
  title: 'Restaurant Ordering System'
  description: 'This is an incomplete API based on API Platform en Symfony.'
  version: '1.0.0-alpha'
